#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Paolo De Rosa and contributors
# SPDX-License-Identifier: MIT
"""R6-07 — the counts that describe this project, DERIVED.

The outward-facing documents (`sbm-deliverables`) state how many review rounds
have run, how many lint rules exist and how many automated checks pass. Those
three numbers have been corrected by hand after every round, and were two
rounds stale when round 6 arrived — sitting inside the very documents that
describe a process built to eliminate stale restated values.

Cowork's proposal, adopted: generate them. A sixth manual correction is a sixth
chance to be wrong.

`--emit` writes `docs/project-counts.json`, which those documents quote and a
check compares. Every number here is read from an artefact that cannot lie
about it:

  rounds  — the review documents in the hand-off series are not in this
            repository, so the round count is read from the CHANGELOG's own
            "Design review round N" headings, which are written per round and
            reviewed as part of the round.
  rules   — docs/lint-catalogue.json, the generated catalogue.
  checks  — the pytest collection count, run rather than remembered.
  gates   — the conformance targets in the Makefile.
"""
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "project-counts.json"


def rounds():
    """The number of completed adversarial review rounds behind this revision.

    This export's CHANGELOG records the history of the ARTEFACTS rather than of
    the review process, so the count cannot be derived from its headings. It is
    a fact about the design study, declared once in `docs/review-rounds.json`
    and quoted by the outward-facing documents so that they cannot restate it
    from memory — which is the drift this whole mechanism exists to prevent.
    """
    return int(json.loads(
        (ROOT / "docs" / "review-rounds.json").read_text(encoding="utf-8"))["completed_rounds"])


def rules():
    return len(json.loads(
        (ROOT / "docs" / "lint-catalogue.json").read_text(encoding="utf-8"))["rules"])


def checks():
    """The pytest total, COLLECTED rather than remembered."""
    r = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q"],
                       cwd=ROOT, capture_output=True, text=True)
    m = re.search(r"^(\d+) tests collected", r.stdout, re.M)
    if not m:
        m = re.search(r"(\d+) tests? collected", r.stdout)
    if not m:
        raise SystemExit("could not read the collected test count from pytest")
    return int(m.group(1))


def gates():
    """The PREREQUISITES of the `conformance` target — the gates themselves,
    not every word on the line."""
    mk = (ROOT / "Makefile").read_text(encoding="utf-8")
    line = mk[mk.index("\nconformance:") + 1:]
    line = line[:line.index("\n")]
    return len(line.split(":", 1)[1].split())


def collect():
    return {"rounds": rounds(), "lint_rules": rules(),
            "automated_checks": checks(), "conformance_gates": gates()}


def main(argv):
    now = collect()
    if "--emit" in argv:
        OUT.write_text(json.dumps(
            {"$comment": (
                "R6-07: GENERATED by scripts/project_counts.py. The outward-facing documents quote "
                "these instead of restating them, because the three numbers had been corrected by hand "
                "after every round and were two rounds stale when round 6 arrived — inside the "
                "documents describing a process built to eliminate exactly that. Regenerate with "
                "`python3 scripts/project_counts.py --emit`."),
             **now}, indent=2) + "\n")
        print(f"[OK] wrote {OUT.relative_to(ROOT)}: {now}")
        return 0
    if not OUT.exists():
        print("[FAIL] docs/project-counts.json is missing — run --emit")
        return 1
    was = {k: v for k, v in json.loads(OUT.read_text()).items()
           if not k.startswith("$")}
    if was != now:
        print(f"[FAIL] docs/project-counts.json is stale: recorded {was}, "
              f"actual {now} — run `scripts/project_counts.py --emit`")
        return 1
    print(f"[OK] project counts current: {now}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
