#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Paolo De Rosa and contributors
# SPDX-License-Identifier: CC-BY-4.0
"""The counts these documents state must match the specification's own.

The executive brief makes claims ABOUT the specification — how many review rounds have
run, how many lint rules exist, how many automated checks pass — and those
three numbers were corrected by hand after every round. They were **two rounds
stale** when round 6 arrived, sitting inside the documents that describe a
process built to eliminate stale restated values. That is the joke this script
exists to stop being.

`sbm-spec` now GENERATES the numbers (`scripts/project_counts.py` ->
`docs/project-counts.json`). This reads that file and checks the prose against
it, so a seventh round updates one place and this fails until the documents
follow.

    python3 check_counts.py            # verify
    python3 check_counts.py --show     # print what the spec currently reports

It deliberately does NOT rewrite the prose. These are outward-facing documents
whose wording is chosen; the numbers appear inside sentences that a generator
would flatten. What must not happen is that they go stale SILENTLY.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
COUNTS = HERE.parent / "docs" / "project-counts.json"



def load():
    if not COUNTS.exists():
        raise SystemExit(
            f"[SKIP] {COUNTS} not found — run scripts/project_counts.py --emit "
            "in the specification root")
    return {k: v for k, v in json.loads(COUNTS.read_text()).items()
            if not k.startswith("$")}


def check(counts):
    problems = []
    brief = (HERE / "executive-brief.md").read_text()
    rules = counts["lint_rules"]
    if f"{rules} rules" not in brief:
        problems.append(f"the brief does not state {rules} lint rules")
    # By maintainer decision (20 September 2026) neither the README nor the
    # brief makes a provenance claim, so the review-round count is not quoted
    # anywhere and is not checked; the brief's one restated number is the rule
    # count, and it states the check count only in words.
    return problems


def main(argv):
    counts = load()
    if "--show" in argv:
        print(json.dumps(counts, indent=2))
        return 0
    problems = check(counts)
    for p in problems:
        print(f"[FAIL] {p}")
    if problems:
        print("\nThe specification reports:", counts)
        print("Update the prose, then re-run. (These numbers are generated by "
              "sbm-spec/scripts/project_counts.py — do not restate them from "
              "memory.)")
        return 1
    print(f"[OK] the walk-back documents match the specification: {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
